/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'street' : string,
  'country' : string,
  'city' : string,
  'postalCode' : bigint,
  'recipient' : string,
  'state' : string,
}
export interface Cart { 'items' : Array<CartItem> }
export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export type Category = { 'shirts' : null } |
  { 'jeans' : null } |
  { 'tshirts' : null };
export interface Product {
  'name' : string,
  'description' : string,
  'category' : Category,
  'price' : bigint,
}
export interface _SERVICE {
  'addItemsToCart' : ActorMethod<[Array<CartItem>], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'checkProductExists' : ActorMethod<[bigint], boolean>,
  'clearCart' : ActorMethod<[], undefined>,
  'getCart' : ActorMethod<[], Cart>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'placeOrder' : ActorMethod<
    [Address],
    { 'orderId' : bigint, 'totalAmount' : bigint }
  >,
  'refillCatalog' : ActorMethod<[Array<Product>], undefined>,
  'removeItemFromCart' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];