/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Category = IDL.Variant({
  'shirts' : IDL.Null,
  'jeans' : IDL.Null,
  'tshirts' : IDL.Null,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
export const Address = IDL.Record({
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Nat,
  'recipient' : IDL.Text,
  'state' : IDL.Text,
});

export const idlService = IDL.Service({
  'addItemsToCart' : IDL.Func([IDL.Vec(CartItem)], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'checkProductExists' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'clearCart' : IDL.Func([], [], []),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'placeOrder' : IDL.Func(
      [Address],
      [IDL.Record({ 'orderId' : IDL.Nat, 'totalAmount' : IDL.Nat })],
      [],
    ),
  'refillCatalog' : IDL.Func([IDL.Vec(Product)], [], []),
  'removeItemFromCart' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Category = IDL.Variant({
    'shirts' : IDL.Null,
    'jeans' : IDL.Null,
    'tshirts' : IDL.Null,
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
  const Address = IDL.Record({
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Nat,
    'recipient' : IDL.Text,
    'state' : IDL.Text,
  });
  
  return IDL.Service({
    'addItemsToCart' : IDL.Func([IDL.Vec(CartItem)], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'checkProductExists' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'clearCart' : IDL.Func([], [], []),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'placeOrder' : IDL.Func(
        [Address],
        [IDL.Record({ 'orderId' : IDL.Nat, 'totalAmount' : IDL.Nat })],
        [],
      ),
    'refillCatalog' : IDL.Func([IDL.Vec(Product)], [], []),
    'removeItemFromCart' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };